// Compiled using marko@4.4.2 - DO NOT EDIT
"use strict";

var marko_template = module.exports = require("marko/src/html").t(__filename);

function render(input, out) {
  var data = input;

  out.w("<div class=\"feature__box__n__feature\"><div class=\"feature__box feature__box2\"></div><div class=\"feature__box feature__box25\"></div><div class=\"row sm__individual__container\"><div class=\"sm__title__container\"><div class=\"sm__title__top_layer\"><img class=\"sm__title__profile_picture\" src=\"/static/images/homepage_avatar.png\" alt=\"Julius Reade Profile Avatar\"><div class=\"sm__title__top_layer__right\"><a class=\"sm__title__username__link\" href=\"https://learningschedule.com/juliusreade\"><h4 class=\"sm__title__username\">juliusreade</h4></a><h5 class=\"sm__title__start_date__container\">March 17th</h5></div><div class=\"sm__title__top_layer__updates\"><h4 class=\"sm__title__top_layer__updates__link\">Updates (7)</h4><h4 class=\"sm__title__top_layer__updates__link\">Tags (9)</h4></div><div class=\"clear\"></div></div><h3 class=\"sm__title__container\"><a class=\"sm__title__a--link\" type=\"button\">When React/Redux Finally Makes Sense!</a></h3><p class=\"sm__title__schedule__summary\">The fourth attempt at my application and by-far my longest. Still so much to learn!</p><div class=\"clear\"></div></div> <ul class=\"sm__tag__outer__container\"><li class=\"sm__tag__text\">#graphql</li><li class=\"sm__tag__text\">#relay</li><li class=\"sm__tag__text\">#elixir</li><li class=\"sm__tag__text\">#phoenixframework</li><li class=\"sm__tag__text\">#rubyonrails</li><li class=\"sm__tag__text\">#csharp</li><li class=\"sm__tag__text\">#redux</li><li class=\"sm__tag__text\">#react</li></ul> <div class=\"sm__update__outer__container\"><ul><p class=\"sm__update__text\"><span class=\"sm__update__text__yolo\"> Apr 01 - Holy Cow. My application officially works! The backend is perfectly connected with the front-end !!!!!! It’s like, the happiest day of my life. Still need to get user authentication to work though...</span></p><p class=\"sm__update__text\"><span class=\"sm__update__text__yolo\"> Mar 30 - Really getting the hang of writing tests and learning about dev dependencies and making mocha, babel and webpack working together. Will be goooood ///// blaahhhh *cough cough* @#TARst3p v</span></p><p class=\"sm__update__text\"> <span class=\"sm__update__text__yolo\"> Mar 27 - I feel like I finally understand react/redux, even though I’ve done it so many times before. Oh, and it’s the first time I managed to successfully build a functioning backend! I can also do async, though I know it’s not well enough. I also learnt SO MUCH vanilla javascript and how to work with objects and arrays, as well as all the nitty gritty details of Javascript. I’m not sure what I want to do anymore, maybe C#? I couldn’t do anymore functional FRP for a while now.</span></p></ul></div></div> </div> ");
}

marko_template._ = render;

marko_template.meta = {};
